defaultNumber: 42

---
spring:
    profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: https://predix-eureka-server.run.aws-usw02-pr.ice.predix.io/eureka
      # ${vcap.services.p-service-registry.credentials.url}/eureka
